# Generated by Django 4.1.7 on 2024-11-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employeeId", models.PositiveBigIntegerField(default=0)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
