# Generated by Django 4.1.7 on 2024-11-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systemCar", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checker", models.CharField(max_length=100)),
            ],
        ),
    ]
